<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-MC" ignored="0" name="RUN ON FIREFOX_UI" tests="2" failures="2" timestamp="03 Jun 2021 04:04:44 GMT" time="43.745" errors="0">
  <testcase name="TC_01_Register" time="9.074" classname="com.nopcommerce.admin.Level_11_Demo_Verify">
    <failure type="java.lang.AssertionError" message="expected [Your registration completed...] but found [Your registration completed]">
      <![CDATA[java.lang.AssertionError: expected [Your registration completed...] but found [Your registration completed]
at commons.AbstractTest.checkEquals(AbstractTest.java:142)
at commons.AbstractTest.verifyEquals(AbstractTest.java:154)
at com.nopcommerce.admin.Level_11_Demo_Verify.TC_01_Register(Level_11_Demo_Verify.java:75)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- TC_01_Register -->
  <testcase name="TC_02_Login" time="23.493" classname="com.nopcommerce.admin.Level_11_Demo_Verify">
    <failure type="java.lang.Throwable" message="Multiple failures (3):
Failure 1 of 3
java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertFalse(Assert.java:65)
	at org.testng.Assert.assertFalse(Assert.java:75)
	at commons.AbstractTest.checkFailed(AbstractTest.java:126)
	at commons.AbstractTest.verifyFalse(AbstractTest.java:136)
	at com.nopcommerce.admin.Level_11_Demo_Verify.TC_02_Login(Level_11_Demo_Verify.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

Failure 2 of 3
java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertFalse(Assert.java:65)
	at org.testng.Assert.assertFalse(Assert.java:75)
	at commons.AbstractTest.checkFailed(AbstractTest.java:126)
	at commons.AbstractTest.verifyFalse(AbstractTest.java:136)
	at com.nopcommerce.admin.Level_11_Demo_Verify.TC_02_Login(Level_11_Demo_Verify.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

Failure 3 of 3
java.lang.AssertionError: expected [false] but found [true]">
      <![CDATA[java.lang.Throwable: Multiple failures (3):
Failure 1 of 3
java.lang.AssertionError: expected [false] but found [true]
at commons.AbstractTest.checkFailed(AbstractTest.java:126)
at commons.AbstractTest.verifyFalse(AbstractTest.java:136)
at com.nopcommerce.admin.Level_11_Demo_Verify.TC_02_Login(Level_11_Demo_Verify.java:89)

Failure 2 of 3
java.lang.AssertionError: expected [false] but found [true]
at commons.AbstractTest.checkFailed(AbstractTest.java:126)
at commons.AbstractTest.verifyFalse(AbstractTest.java:136)
at com.nopcommerce.admin.Level_11_Demo_Verify.TC_02_Login(Level_11_Demo_Verify.java:90)

Failure 3 of 3
java.lang.AssertionError: expected [false] but found [true]
at commons.AbstractTest.checkFailed(AbstractTest.java:126)
at commons.AbstractTest.verifyFalse(AbstractTest.java:136)
at com.nopcommerce.admin.Level_11_Demo_Verify.TC_02_Login(Level_11_Demo_Verify.java:91)
... Removed 87 stack frames]]>
    </failure>
  </testcase> <!-- TC_02_Login -->
</testsuite> <!-- RUN ON FIREFOX_UI -->
